## Link of Data
https://www.kaggle.com/datasets/fedesoriano/electric-power-consumption

## Importing Necessary libraries

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import root_mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder

## Loading Data And Overview

In [4]:
dt = pd.read_csv("powerconsumption.csv")
dt.head(20)

,Datetime,Temperature,Humidity,WindSpeed,GeneralDiffuseFlows,DiffuseFlows,PowerConsumption_Zone1,PowerConsumption_Zone2,PowerConsumption_Zone3
0,1/1/2017 0:00,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386
1,1/1/2017 0:10,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434
2,1/1/2017 0:20,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373
3,1/1/2017 0:30,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711
4,1/1/2017 0:40,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964
5,1/1/2017 0:50,5.853,76.9,0.081,0.059,0.108,26624.81013,17416.41337,18130.12048
6,1/1/2017 1:00,5.641,77.7,0.080,0.048,0.096,25998.98734,16993.31307,17945.06024
7,1/1/2017 1:10,5.496,78.2,0.085,0.055,0.093,25446.07595,16661.39818,17459.27711
8,1/1/2017 1:20,5.678,78.1,0.081,0.066,0.141,24777.72152,16227.35562,17025.54217
9,1/1/2017 1:30,5.491,77.3,0.082,0.062,0.111,24279.49367,15939.20973,16794.21687
10,1/1/2017 1:40,5.516,77.5,0.081,0.051,0.108,23896.70886,15435.86626,16638.07229
11,1/1/2017 1:50,5.471,76.7,0.083,0.059,0.126,23544.30380,15213.37386,16395.18072
12,1/1/2017 2:00,5.059,78.6,0.081,0.070,0.096,23003.54430,15169.60486,16117.59036
13,1/1/2017 2:10,4.968,78.8,0.084,0.070,0.134,22329.11392,14710.03040,15822.65060
14,1/1/2017 2:20,4.975,78.9,0.083,0.055,0.152,22092.15190,14421.88450,15672.28916
15,1/1/2017 2:30,4.897,79.1,0.083,0.070,0.096,21903.79747,14104.55927,15597.10843
16,1/1/2017 2:40,5.020,79.7,0.081,0.051,0.134,21685.06329,13965.95745,15510.36145
17,1/1/2017 2:50,5.407,78.5,0.082,0.062,0.163,21484.55696,13612.15805,15336.86747
18,1/1/2017 3:00,5.169,77.9,0.083,0.066,0.108,21107.84810,13535.56231,15140.24096
19,1/1/2017 3:10,5.081,77.7,0.084,0.051,0.130,20998.48101,13371.42857,15059.27711

In [5]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52416 entries, 0 to 52415
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Datetime                52416 non-null  object
 1   Temperature             52416 non-null  float64
 2   Humidity                52416 non-null  float64
 3   WindSpeed               52416 non-null  float64
 4   GeneralDiffuseFlows     52416 non-null  float64
 5   DiffuseFlows            52416 non-null  float64
 6   PowerConsumption_Zone1  52416 non-null  float64
 7   PowerConsumption_Zone2  52416 non-null  float64
 8   PowerConsumption_Zone3  52416 non-null  float64
dtypes: float64(8), object(1)
memory usage: 3.6+ MB

In [6]:
dt.describe().T

,count,mean,std,min,25%,50%,75%,max
Temperature,52416.0,18.810024,5.815476,3.247000,14.410000,18.780000,22.890000,40.01000
Humidity,52416.0,68.259518,15.551177,11.340000,58.310000,69.860000,81.400000,94.80000
WindSpeed,52416.0,1.959489,2.348862,0.050000,0.078000,0.086000,4.915000,6.48300
GeneralDiffuseFlows,52416.0,182.696614,264.400960,0.004000,0.062000,5.035500,319.600000,1163.00000
DiffuseFlows,52416.0,75.028022,124.210949,0.011000,0.122000,4.456000,101.000000,936.00000
PowerConsumption_Zone1,52416.0,32344.970564,7130.562564,13895.696200,26310.668692,32265.920340,37309.018185,52204.39512
PowerConsumption_Zone2,52416.0,21042.509082,5201.465892,8560.081466,16980.766032,20823.168405,24713.717520,37408.86076
PowerConsumption_Zone3,52416.0,17835.406218,6622.165099,5935.174070,13129.326630,16415.117470,21624.100420,47598.32636

In [7]:
dt.shape

(52416, 9)

In [8]:
dt.columns

Index(['Datetime', 'Temperature', 'Humidity', 'WindSpeed',
       'GeneralDiffuseFlows', 'DiffuseFlows', 'PowerConsumption_Zone1',
       'PowerConsumption_Zone2', 'PowerConsumption_Zone3'],
      dtype='object')

## Preprocessing

In [9]:
dt.head(10)

,Datetime,Temperature,Humidity,WindSpeed,GeneralDiffuseFlows,DiffuseFlows,PowerConsumption_Zone1,PowerConsumption_Zone2,PowerConsumption_Zone3
0,1/1/2017 0:00,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386
1,1/1/2017 0:10,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434
2,1/1/2017 0:20,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373
3,1/1/2017 0:30,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711
4,1/1/2017 0:40,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964
5,1/1/2017 0:50,5.853,76.9,0.081,0.059,0.108,26624.81013,17416.41337,18130.12048
6,1/1/2017 1:00,5.641,77.7,0.080,0.048,0.096,25998.98734,16993.31307,17945.06024
7,1/1/2017 1:10,5.496,78.2,0.085,0.055,0.093,25446.07595,16661.39818,17459.27711
8,1/1/2017 1:20,5.678,78.1,0.081,0.066,0.141,24777.72152,16227.35562,17025.54217
9,1/1/2017 1:30,5.491,77.3,0.082,0.062,0.111,24279.49367,15939.20973,16794.21687

#### Feature Extraction

In [10]:
dt['Datetime'] = pd.to_datetime(dt['Datetime'], format='%m/%d/%Y %H:%M')

In [11]:
dt['Month'] = dt['Datetime'].dt.month

In [12]:
dt['TimeFloat'] = dt['Datetime'].dt.hour + dt['Datetime'].dt.minute / 60

In [13]:
dt = dt.drop(columns=['Datetime'], axis= 1)

In [14]:
dt.head()

,Temperature,Humidity,WindSpeed,GeneralDiffuseFlows,DiffuseFlows,PowerConsumption_Zone1,PowerConsumption_Zone2,PowerConsumption_Zone3,Month,TimeFloat
0,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386,1,0.000000
1,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434,1,0.166667
2,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373,1,0.333333
3,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711,1,0.500000
4,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964,1,0.666667

## Modeling

In [15]:
X = dt.drop(columns=['PowerConsumption_Zone1','PowerConsumption_Zone2','PowerConsumption_Zone3'], axis= 1)
y1 = dt['PowerConsumption_Zone1']
y2 = dt['PowerConsumption_Zone2']
y3 = dt['PowerConsumption_Zone3']

#### Polynomial Rregression

In [16]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

degree = 5

X_train, X_test, y1_train, y1_test = train_test_split(X, y1, test_size=0.2, random_state=42)
_, _, y2_train, y2_test = train_test_split(X, y2, test_size=0.2, random_state=42)
_, _, y3_train, y3_test = train_test_split(X, y3, test_size=0.2, random_state=42)

def poly_regression(X_train, X_test, y_train, y_test, degree=2):
    model = make_pipeline(PolynomialFeatures(degree), LinearRegression())
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    rmse = root_mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    return rmse, r2

rmse1, r2_1 = poly_regression(X_train, X_test, y1_train, y1_test, degree)
print(f"Zone1 - RMSE: {rmse1:.2f}, R2: {r2_1:.2f}")

rmse2, r2_2 = poly_regression(X_train, X_test, y2_train, y2_test, degree)
print(f"Zone2 - RMSE: {rmse2:.2f}, R2: {r2_2:.2f}")

rmse3, r2_3 = poly_regression(X_train, X_test, y3_train, y3_test, degree)
print(f"Zone3 - RMSE: {rmse3:.2f}, R2: {r2_3:.2f}")

Zone1 - RMSE: 2302.64, R2: 0.89
Zone2 - RMSE: 2199.23, R2: 0.82
Zone3 - RMSE: 2446.48, R2: 0.86

#### Random Forest

In [17]:
from sklearn.ensemble import RandomForestRegressor

def rf_regression(X_train, X_test, y_train, y_test):
    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    rmse = root_mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    return rmse, r2

rf_rmse1, rf_r2_1 = rf_regression(X_train, X_test, y1_train, y1_test)
print(f"Random Forest Zone1 - RMSE: {rf_rmse1:.2f}, R2: {rf_r2_1:.2f}")

rf_rmse2, rf_r2_2 = rf_regression(X_train, X_test, y2_train, y2_test)
print(f"Random Forest Zone2 - RMSE: {rf_rmse2:.2f}, R2: {rf_r2_2:.2f}")

rf_rmse3, rf_r2_3 = rf_regression(X_train, X_test, y3_train, y3_test)
print(f"Random Forest Zone3 - RMSE: {rf_rmse3:.2f}, R2: {rf_r2_3:.2f}")

Random Forest Zone1 - RMSE: 1137.72, R2: 0.97
Random Forest Zone2 - RMSE: 1011.16, R2: 0.96
Random Forest Zone3 - RMSE: 805.66, R2: 0.99